pipeline:
  agent:
    any:
  stages:
    - stage: "Build spring-boot-docker-demo-api using gradle build"
      steps:
        - git "https://github.com/arindambardhan/spring-boot-docker-demo-api.git"
        - sh './gradlew clean build'
