spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://database-1.cbdcyxvfnixl.us-east-1.rds.amazonaws.com:1433;dataBase=practisejpa;userName=admin;password=12345678;trustServerCertificate=true
    continue-on-error: true
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
      connection-timeout: 3000
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 9090
